unicat_admin:
    path: /
    defaults:
        _controller: UnicatModule:AdminUnicat:index

unicat_admin.configuration:
    path: /{configuration}/
    defaults:
        _controller: UnicatModule:AdminUnicat:configuration

unicat_admin.configuration.settings:
    path: /{configuration}/settings/
    defaults:
        _controller: UnicatModule:AdminUnicat:configurationSettings

# Taxonomy
unicat_admin.taxonomies_index:
    path: /{configuration}/taxonomy/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:index

unicat_admin.taxonomy_create:
    path: /{configuration}/taxonomy/create/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:create

unicat_admin.taxonomy:
    path: /{configuration}/taxonomy/{id}/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:taxonomy
    requirements:
        id: \d+

unicat_admin.taxonomy_with_parent_id:
    path: /{configuration}/taxonomy/{id}/{parent_id}/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:taxonomy
    requirements:
        parent_id: \d+
        id: \d+

unicat_admin.taxonomy_edit:
    path: /{configuration}/taxonomy/{id}/edit/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:edit
    requirements:
        id: \d+

unicat_admin.taxon:
    path: /{configuration}/taxonomy/{taxonomy_id}/taxon_{id}/
    defaults:
        _controller: UnicatModule:AdminTaxonomy:taxonEdit
    requirements:
        id: \d+
        taxonomy_id: \d+

# Attributes
unicat_admin.attributes_index:
    path: /{configuration}/attributes/
    defaults:
        _controller: UnicatModule:AdminAttributes:index

unicat_admin.attributes_group_create:
    path: /{configuration}/attributes/create_group/
    defaults:
        _controller: UnicatModule:AdminAttributes:createGroup

unicat_admin.attributes:
    path: /{configuration}/attributes/group_{group_id}/
    defaults:
        _controller: UnicatModule:AdminAttributes:group
    requirements:
        group_id: \d+

unicat_admin.attribute:
    path: /{configuration}/attributes/group_{group_id}/{id}/
    defaults:
        _controller: UnicatModule:AdminAttributes:edit
    requirements:
        group_id: \d+
        id: \d+

# Items
unicat_admin.item_create:
    path: /{configuration}/item_create/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

unicat_admin.item_create_in_taxon:
    path: /{configuration}/item_create/{default_taxon_id}/
    requirements:
        default_taxon_id: \d+
    defaults:
        _controller: UnicatModule:AdminUnicat:itemCreate

unicat_admin.item_edit:
    path: /{configuration}/item_{id}/
    defaults:
        _controller: UnicatModule:AdminUnicat:itemEdit
    requirements:
        id: \d+
