
unicat.root:
    path: /
    defaults:
        _controller: UnicatModule:Unicat:index

unicat.index:
    path: /{slug}
    defaults:
        _controller: UnicatModule:Unicat:index
        slug: null
    requirements:
        slug: '.+'

unicat.item_in_taxonomy:
    path: /{taxonomySlug}/{itemSlug}.html
    defaults:
        _controller: UnicatModule:Unicat:item
    requirements:
        itemSlug: '.+'
        taxonomySlug: '.+'

unicat.item:
    path: /{itemSlug}.html
    defaults:
        _controller: UnicatModule:Unicat:item
    requirements:
        itemSlug: '.+'
